{
 "title": "Network Health Detail",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Device Name",
    "query": {
     "query": "label_values(interface_admin_status,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BGP Received Prefixes",
   "type": "stat",
   "description": "Prefixes received for all BGP instances",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bgp_session_prefixes_received{device=\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Received Prefixes",
   "type": "timeseries",
   "description": "Received Prefix Count",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "bgp_session_prefixes_received{device=\"$device_name\"}",
     "legendFormat": "{{neighbor_address}}"
    }
   ]
  },
  {
   "title": "BGP Advertised Prefixes",
   "type": "stat",
   "description": "Prefixes received for all BGP instances",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bgp_session_prefixes_sent{device=\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Advertised Prefixes",
   "type": "timeseries",
   "description": "Advertised Prefix Count",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "bgp_session_prefixes_sent{device=\"$device_name\"}",
     "legendFormat": "{{neighbor_address}}"
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "table",
   "description": "Table of BGP Peers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bgp_session_state{device=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Operational State Timeline",
   "type": "state-timeline",
   "description": "Timeline of the operational state as read by gNMI",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "interface_admin_status{device=\"$device_name\"}",
     "legendFormat": "{{interface}} State"
    }
   ]
  }
 ]
}