auth_enabled: false

server:
  http_listen_port: 3001

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2023-07-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  allow_structured_metadata: true
  discover_service_name: []
  discover_log_levels: false

ruler:
  wal:
    dir: /loki/ruler-wal
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  storage:
    type: local
    local:
      directory: /rules
  alertmanager_url: http://alertmanager:9093
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write

analytics:
 reporting_enabled: false
