{
 "title": "Workshop Lab 2026",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(device_uptime,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Admin State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "interface_admin_state{intf_role=\"peer\", name=~\"ethernet-1/1([0-2])?\", device=\"$device\"}",
     "legendFormat": "{{device}}-{{name}}"
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(interface_out_octets{name=~\"ethernet-1/1([0-2])?\", device=\"$device\"}[$__rate_interval]) * 8",
     "legendFormat": "out-{{device}}-{{name}}"
    },
    {
     "expr": "rate(interface_in_octets{name=~\"ethernet-1/1([0-2])?\", device=\"$device\"}[$__rate_interval]) * 8 * -1",
     "legendFormat": "in-{{device}}-{{name}}"
    }
   ]
  },
  {
   "title": "Interface Operational Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "interface_oper_state{intf_role=\"peer\", name=~\"ethernet-1/1([0-2])?\", device=\"$device\"}",
     "legendFormat": "{{device}}-{{name}}"
    }
   ]
  },
  {
   "title": "Interface Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{device=\"$device\"} != \"license\"\n|= \"interface\"\n|~ \"down|up|admin-state\"\n| line_format \"{{.device}} {{.facility_label}} | {{__line__}}\""
    }
   ]
  }
 ]
}