---
- name: Show Inventory
  hosts: "{{ do_droplet_name }}"
  gather_facts: false
  vars:
    do_droplet_name: "{{ lookup('ansible.builtin.env', 'DO_DROPLET_NAME', default='netobs-droplet') }}"
  tasks:
    - name: Show SSH command
      ansible.builtin.debug:
        msg: "ssh -o StrictHostKeyChecking=no -i {{ lookup('ansible.builtin.env', 'SSH_KEY_PATH') }} root@{{ ansible_host }}"
