---
#### Bootstrap netobs-droplet
- name: Bootstrap netobs-droplet
  hosts: "netobs-droplet"
  gather_facts: false
  tasks:
    - name: Wait for connection to netobs-droplet
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Bootstrap system
      ansible.builtin.import_tasks: tasks/bootstrap.yml

#### Setup netobs-droplet
- name: Setup netobs app
  hosts: netobs-droplet
  vars:
    ansible_python_interpreter: /root/miniconda/bin/python
    netobs_repo_dir: /root/network-observability-lab
  environment:
    PATH: "/root/miniconda/bin:/root/.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Clone network-observability-lab
      ansible.builtin.git:
        repo: "{{ lookup('env', 'NETOBS_REPO' | default('https://github.com/network-observability/network-observability-lab.git')) }}"
        dest: "{{ netobs_repo_dir }}"
        version: "{{ lookup('env', 'NETOBS_BRANCH' | default('main')) }}"

    - name: Copy .env file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../.env"
        dest: "{{ netobs_repo_dir }}/.env"
        mode: "0644"

    - name: Copy the keep_api_key file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../keep_api_key"
        dest: "{{ item }}"
      loop:
        - "{{ netobs_repo_dir }}/chapters/batteries-included/alertmanager/keep_api_key"
        - "{{ netobs_repo_dir }}/chapters/ch9/alertmanager/keep_api_key"
        - "{{ netobs_repo_dir }}/chapters/ch9-completed/alertmanager/keep_api_key"
      when:
        - lab_scenario == "batteries-included"

    - name: Deploy netobs app
      ansible.builtin.import_tasks: tasks/deploy.yml
